In [68]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [70]:
 df, df2, df3 = pd.read_csv('fourGreta.csv'), pd.read_csv('data1.csv'), pd.read_csv('data2.csv')
df = df.iloc[-33:,:]
hold = df.iloc[0,:]
df = df.iloc[1:,:]
assert len(df) == len(df2) == len(df3)
df['GRUBTCRTN'] = df2.GRUBTCRTN.values
df['GRUBTCPRC'] = df3.GRUBTCPRC.values
# get our starting point price at 2018-03-05
start_price = hold['price']
print(start_price)
prices = df['price'].values
dates = df['date'].values
return_strategy = df['GRUBTCRTN'].values
price_strategy = df['GRUBTCPRC'].values

11573.3


# Test return if you only holded bitcoin from 2018-03-05

In [72]:
 # lost 4143.58 regarding USD by holding, investment worth around 61% of value, so 6636
    
# 10779.9 - 100
# 6636.32 - x
11573.3 - prices[-1]
#(6636.32 * 100)/11573.3

4936.98

# Test with return data

In [27]:
return_strategy

array([0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0], dtype=int64)

In [59]:
prices

array([10779.9 ,  9965.57,  9395.01,  9337.55,  8866.  ,  9578.63,
        9205.12,  9194.85,  8269.81,  8300.86,  8338.35,  7916.88,
        8223.68,  8630.65,  8913.47,  8929.28,  8728.47,  8879.62,
        8668.12,  8495.78,  8209.4 ,  7833.04,  7954.48,  7165.7 ,
        6890.52,  6973.53,  6844.23,  7083.8 ,  7456.11,  6853.84,
        6811.47,  6636.32])

In [75]:
prices_test = np.append([start_price], prices)
prices_test = prices_test[:-1]

In [78]:
prices_test

array([11573.3 , 10779.9 ,  9965.57,  9395.01,  9337.55,  8866.  ,
        9578.63,  9205.12,  9194.85,  8269.81,  8300.86,  8338.35,
        7916.88,  8223.68,  8630.65,  8913.47,  8929.28,  8728.47,
        8879.62,  8668.12,  8495.78,  8209.4 ,  7833.04,  7954.48,
        7165.7 ,  6890.52,  6973.53,  6844.23,  7083.8 ,  7456.11,
        6853.84,  6811.47])

In [111]:
def strategy(my_strategy):
    # ok lets go
    btc = 1
    bank = -start_price

    for i in range(len(price_strategy)):
        if my_strategy[i] == 1:
            btc += 1
            bank -= prices_test[i]
        elif my_strategy[i] == 0:
            if btc == 0:
                pass
            elif btc > 0:
                btc = 0
                bank += prices_test[i]

    return btc, bank

In [112]:
strategy(return_strategy)

(0, -41885.92)

In [113]:
strategy(price_strategy)

(0, 0.0)

In [123]:
coins = []
banks = []

for i in range(1000000):

    x = np.random.choice(2, len(return_strategy))
    
    zz, zzz = strategy(x)
    coins.append(zz*prices[-1])
    banks.append(zzz)

coins = np.array(coins)
banks = np.array(banks)

In [128]:
coins.mean() + banks.mean()

-69594.49249006005

In [129]:
"""
INITIALIZE bitcoin_amount -> 1
INITIALIZE bank_holding -> -11573.3

FOR day in testing_period:  
    IF strategy[day] == buy:
        bitcoin_amount -> bitcoin_amount + 1
        bank_holding -> bank_holding - price[day]
    ELSE IF strategy[day] == sell:
        IF bitcoin_amount == 0:
            DO NOTHING
        ELSE IF bitcoin_amount > 0:
            bitcoin_amount -> 0
            bank_holding -> bank_holding + price[day]
"""        
    

'\nINITIALIZE bitcoin_amount -> 1\nINITIALIZE bank_holding -> -11573.3\n\nFOR day in testing_period:  \n    IF strategy[day] == buy:\n        bitcoin_amount -> bitcoin_amount + 1\n        bank_holding -> bank_holding - price[day]\n    ELSE IF strategy[day] == sell:\n        IF bitcoin_amount == 0:\n            DO NOTHING\n        ELSE IF bitcoin_amount > 0:\n            bitcoin_amount -> 0\n            bank_holding -> bank_holding + price[day]\n'

In [131]:
banks.mean()

-76239.11452638004